"""add sleep and respiratory fields to whoop_data

Revision ID: fceb519ee51b
Revises: 38f1a06fba89
Create Date: 2026-05-20 23:54:39.575833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fceb519ee51b'
down_revision = '38f1a06fba89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whoop_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respiratory_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sleep_needed_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sleep_consistency_pct', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sleep_efficiency_pct', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sleep_disturbances', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whoop_data', schema=None) as batch_op:
        batch_op.drop_column('sleep_disturbances')
        batch_op.drop_column('sleep_efficiency_pct')
        batch_op.drop_column('sleep_consistency_pct')
        batch_op.drop_column('sleep_needed_hours')
        batch_op.drop_column('respiratory_rate')

    # ### end Alembic commands ###
